### ISSUE TITLE
install_exagear.sh is broken

### ISSUE THREAD

**Issue by ShadityZ** [ShadityOS/ShadityOS#1]
install_exagear.sh is broken

messes up apt and makes it hard to install anything

**Comment by ShadowNightX** [comment]
Updated readme

**Comment by ShadowNightX** [comment]
I have created a new repository called [exagear-rpi](https://github.com/ShadowNightX/exagear-rpi).  This repository contains an alternate, tested script which is confirmed to work with ShadityOS. Plans to merge them in the next update.

**Comment by ShadowNightX** [comment]
Planned for v1.0.1. Updates when version is released

**Comment by ShadityZ** [comment]
v1.0.1 Patch has been pushed! Closing issue
