### ISSUE TITLE
using "~" for the home directory doesn't work

### ISSUE THREAD

**Issue by ShadityZ** [ShadityOS/ShadityOS#2]
ANSWER: Just learn to do "cd" instead of "cd ~" it is quicker and works! :)

When I try to use the ```~``` symbol to indicate the home directory, it doesn't work, providing the following error:
```
bash: cd: ~: No such file or directory
```

**Comment by ShadowNightX** [comment]
After Googling, I have found on some distros the ```cd``` command sometimes redirects to the home directory. If possible, I plan to make changes to either the ```cd``` binary or add an alias to the ```.bashrc``` of the user "pi" so that when running ```cd ~``` you will be sent to the home directory.

**Comment by ShadowNightX** [comment]
Confirmed. Bug fix is scheduled for v1.0.1. Issue will be closed when patch is released

**Comment by ShadowNightX** [comment]
More Googling, found "~" is only on bash. Maybe using zsh? Checking...

**Comment by ShadowNightX** [comment]
Delaying to v1.0.2 ... Need more time to investigate

**Comment by ShadityZ** [comment]
Nevermind... Unknown problem source. Wont be fixed unless problem source can be identified. just learn to use "cd" instead of "cd ~"
