### ISSUE TITLE
Extremely Sluggish First Boot on RPi 4

### ISSUE THREAD

**Issue by ShadityZ** [ShadityOS/ShadityOS#3]
When booting up RPi 4 4GB with ShadityOS, initial boot is slow and performance after that is sluggish until a reboot.

**Comment by ShadowNightX** [comment]
Weird... Unsure what is causing this. Investigation is under way

**Comment by ShadityZ** [comment]
Komorebi has been reported to be sluggish on low-end systems, *cough, cough* the raspberry pi. But checking system resources, komorebi is only just using 1% cpu and 15MB of RAM... Just a report... I need to do more research

**Comment by ShadityZ** [comment]
Issue seems to be related with #4 where disk integrity check happens but is slow, and happens at random times. Very weird and confusing. Even after fixing issue 4, it still acts slow. I believe there are multiple issues that make each other worse.

**Comment by ShadityZ** [comment]
Really need extra help on this one. I have spent the past few days but have had no success.

**Comment by ShadityZ** [comment]
Very mind boggling... I plan to see how it fares on the soon to be releases v1.1.0. Maybe might get different results, really confused on this one. Help of any sorts is really appreciated

**Comment by ShadityZ** [comment]
Lightbulb moment! This is mainly down to many gnome setup programs, pishrink _AND_ systemd, starting up countless services to help out the gnome setup programs. Yeah. It took a while, but I found the solution.

**Comment by ShadityZ** [comment]
If you have decent cooling, you could overclock the pi for better performance. By default however, ShadityOS does not come with an overclock, so you will have to test it your self. This problem is specific to the first boot, and you don't see these problems after the reboot.

**Comment by ShadityZ** [comment]
Leaving issue pinned for new users, but closing it now...
